[project]
name = "mcpserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.22.0",
    "fastmcp>=2.2.7",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "openai>=1.77.0",
    "pillow>=11.2.1",
]
